#ifndef ERRORMESSAGE_PRJ_H_INCLUDED
#define ERRORMESSAGE_PRJ_H_INCLUDED

#define ERROR_BUF_SIZE 4

#define ERROR_MESSAGE_LIST \
   ERROR_MESSAGE_ENTRY(MUXSHORT, ERROR_STOP) \
   ERROR_MESSAGE_ENTRY(BALANCER_FAIL, ERROR_STOP) \
   ERROR_MESSAGE_ENTRY(CELL_POLARITY, ERROR_STOP) \
   ERROR_MESSAGE_ENTRY(CELL_OVERVOLTAGE, ERROR_STOP) \

#endif // ERRORMESSAGE_PRJ_H_INCLUDED
